project: venus-tcp-can-bridge
git_branch: main
python:
  name: venus-tcp-can-bridge
  version: 1.0.0
  author: "Kyle Hans Brockmann"
  author_email: kyle.brockmann@gmail.com
  classifiers: []
  description: CAN TCP bridge for Venus
  entry_points:
    console_scripts:
      - venus_can_send = canmqtt.publish:main
      - venus_can_receive = canmqtt.receive:main